apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector: 
    matchLabels: 
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: junniepat/udagram-api-user:latest
        name: backend-user
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "500m"                  
        env:
        - name: URL
          value: a219c5656862d434ab574c6d0c6d4dd9-339968.us-east-2.elb.amazonaws.com:8100
        - name: AWS_BUCKET
          value: pat-udagram
        - name: AWS_PROFILE
          value: default
        - name: AWS_REGION
          value: us-east-2
        - name: JWT_SECRET
          value: helloworld
        - name: POSTGRESS_DB
          value: postgres
        - name: POSTGRESS_HOST
          value: postgres.cawwlhcpeugd.us-east-2.rds.amazonaws.com
        - name: POSTGRESS_PASSWORD
          value: udagram1
        - name: POSTGRESS_USERNAME
          value: udagram1   
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret  