version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: 'udagramproject'
      POSTGRES_PASSWORD: 'udagramPassword'
      POSTGRES_DB: 'udagramproject' 
      POSTGRES_HOST: 'udagramproject.cawwlhcpeugd.us-east-2.rds.amazonaws.com'
      AWS_REGION: 'us-east-2' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'udagrampatproject'
      JWT_SECRET: 'a simple secret'
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: 'udagramproject'
      POSTGRES_PASSWORD: 'udagramPassword'
      POSTGRES_DB: 'udagramproject' 
      POSTGRES_HOST: 'udagramproject.cawwlhcpeugd.us-east-2.rds.amazonaws.com'
      AWS_REGION: 'us-east-2'    
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'udagrampatproject'
      JWT_SECRET: 'a simple secret'
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"